### ISSUE TITLE
Shrouds not working properly

### ISSUE THREAD

**Issue by KingOf-Death** [Aurilux/Shrouds#1]
Every time I try to activate the shroud, it will spit back out the items I give it, despite the beacons activating using those same items with absolutely no issue. I've read that the shrouds operate identically to beacons aside from their targets and effects, so I know it's not a problem with the materials I'm using. I've tried activating the shrouds alone, and I've tried using a variety of different items to activate the shroud. I've tried iron, gold and netherite ingots, emeralds, and diamonds to activate them, and none of them worked. I get to the screen where I can select the debuff to apply to enemies, and I input the items, and then when I click the checkbox, it just gives me back the item I used and doesn't activate the debuff.

**Comment by Aurilux** [comment]
Can you either pastebin an error log or link a video of this issue?

**Comment by KingOf-Death** [comment]
I'll have the video out shortly. I recorded, but I need to compress it to 10MB or less.

**Comment by KingOf-Death** [comment]
https://user-images.githubusercontent.com/87248892/125180363-d7790300-e1be-11eb-9f16-3c324bc2cb56.mp4

not sure if this'll do but here

**Comment by Aurilux** [comment]
I see. My initial idea is that the problem is caused by whatever mod you have that is adding that little box to the corner of the checkmark. Try removing that mod and see if the issue remains. If it does, send me a pastebin link of the debug log so I can take a look.

**Comment by KingOf-Death** [comment]
I feel as though it'll be a long and unnecessary process which will ultimately waste both of our time, and you have more important things to do. I should close this thread and let you tend to your own business.
